In [2]:
import torch

In [3]:
x = torch.arange(4, dtype = torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [4]:
A = torch.randn(25).reshape(5, 5)
A.sum()

tensor(-1.6603)

In [5]:
A_sum0 = A.sum(axis = 0)
A_sum0

tensor([ 0.6064, -0.4587, -1.5969, -2.3894,  2.1783])

In [6]:
A_sum1 = A.sum(axis = 1)
A_sum1

tensor([-0.1704,  0.8984,  0.5965,  0.5777, -3.5625])

In [10]:
A.mean(axis = 0)

(tensor([ 0.1213, -0.0917, -0.3194, -0.4779,  0.4357]), 25)

In [13]:
sum_A = A.sum(axis = 1, keepdim = True)
sum_A.shape

torch.Size([5, 1])

In [14]:
A / sum_A

tensor([[ 2.0134, -4.4354,  9.2450,  1.0582, -6.8811],
        [-0.0449,  0.3319, -0.2370, -0.3834,  1.3334],
        [ 0.4687, -2.0278,  2.3019, -0.7519,  1.0092],
        [ 2.0125,  0.8809,  0.0278, -1.3559, -0.5653],
        [ 0.1270,  0.2279,  0.3362,  0.1776,  0.1312]])

In [16]:
A == A.cumsum(axis = 0)

tensor([[ True,  True,  True,  True,  True],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]])