In [1]:
import torch

In [2]:
X = torch.ones((2, 3, 4))
len(X)

2

In [5]:
A = torch.randn((5,4))
sum_A = A.sum(0, True)
A / sum_A

tensor([[ 0.4250,  1.0015, -0.4008, -1.3880],
        [ 0.0922,  1.1634,  0.9237,  1.5540],
        [-0.0299, -2.1818, -1.8549, -1.6959],
        [-0.0161,  0.4360,  0.9930,  1.3330],
        [ 0.5288,  0.5809,  1.3390,  1.1968]])

In [6]:
B = torch.randn(2,3,4)
B.sum(0), B.sum(1), B.sum(2)

(tensor([[ 2.1456, -0.1921,  1.4645, -1.4812],
         [ 1.3936,  1.4382,  2.2070, -1.3444],
         [-0.5907, -0.5172, -2.3456, -0.4400]]),
 tensor([[ 1.0005, -0.3614,  0.9786, -0.5134],
         [ 1.9480,  1.0902,  0.3473, -2.7522]]),
 tensor([[ 1.3373,  3.8215, -4.0546],
         [ 0.5994, -0.1270,  0.1610]]))

In [7]:
B.norm()

tensor(4.7508)