In [1]:
import sys
sys.path.append(r"C:\Users\ss666\OneDrive\MyJob\Maching_Learning\D2L")
sys.path

['c:\\Users\\ss666\\OneDrive\\MyJob\\Maching_Learning\\D2L\\Chapter_3\\3.2',
 'd:\\ProgramData\\Anaconda3\\python38.zip',
 'd:\\ProgramData\\Anaconda3\\DLLs',
 'd:\\ProgramData\\Anaconda3\\lib',
 'd:\\ProgramData\\Anaconda3',
 '',
 'd:\\ProgramData\\Anaconda3\\lib\\site-packages',
 'd:\\ProgramData\\Anaconda3\\lib\\site-packages\\locket-0.2.1-py3.8.egg',
 'd:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32',
 'd:\\ProgramData\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'd:\\ProgramData\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'd:\\ProgramData\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\ss666\\.ipython',
 'C:\\Users\\ss666\\AppData\\Roaming\\Python\\Python38\\site-packages',
 'C:\\Users\\ss666\\OneDrive\\MyJob\\Maching_Learning\\D2L']

In [2]:
import torch
import tools.generate_data as gd
import tools.plot as plot

In [3]:
ground_true_w: torch.Tensor = torch.tensor([2, -3.4])
ground_true_b: float =  4.2
features, labels = gd.synthetic_data(ground_true_w, ground_true_b, 1000)
features, labels

(tensor([[-0.1369, -0.1319],
         [ 1.4091, -0.5196],
         [ 0.5218, -2.1932],
         ...,
         [ 0.6645,  1.5270],
         [ 0.0335,  0.3029],
         [ 0.5063, -0.4754]]),
 tensor([[ 4.3798e+00],
         [ 8.7970e+00],
         [ 1.2703e+01],
         [ 7.5156e+00],
         [ 4.8344e+00],
         [ 8.2728e-01],
         [ 2.4844e+00],
         [-3.5492e+00],
         [ 4.0026e+00],
         [ 1.9970e+00],
         [ 7.2482e+00],
         [ 7.2202e+00],
         [ 5.3082e+00],
         [ 5.5023e+00],
         [ 5.0273e+00],
         [ 1.2688e+01],
         [ 1.9544e+00],
         [-4.3443e+00],
         [ 7.6854e+00],
         [ 7.3797e+00],
         [ 5.8663e-01],
         [ 2.7360e+00],
         [ 3.2983e+00],
         [ 3.1517e+00],
         [ 4.7225e+00],
         [ 5.4137e+00],
         [ 5.2787e+00],
         [-5.7251e-01],
         [ 2.0394e+00],
         [ 9.5901e+00],
         [ 6.9546e+00],
         [-8.8175e-02],
         [ 4.4164e+00],
         [ 1.0915e

In [4]:
batch_size = 10
for X, y in gd.data_iter(batch_size, features, labels):
    print(X, "\n", y)
    break

tensor([[-0.5489, -0.4508],
        [-2.3262,  0.0253],
        [-1.1652, -1.0341],
        [ 1.9169,  0.0283],
        [-0.3315,  0.2693],
        [ 0.7086,  1.0191],
        [ 1.2003, -0.1211],
        [ 2.0647,  0.9354],
        [-1.9989, -3.1008],
        [-0.5358, -0.0256]]) 
 tensor([[ 4.6407],
        [-0.5332],
        [ 5.3970],
        [ 7.9263],
        [ 2.6251],
        [ 2.1289],
        [ 7.0237],
        [ 5.1607],
        [10.7403],
        [ 3.2309]])
