In [1]:
import torch
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x, y


(tensor([1., 2., 4., 8.]), tensor([2, 2, 2, 2]))

In [2]:
x + y, x - y, x * y,x / y,x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [3]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [4]:
X = torch.randn(3, 4)
Y = torch.arange(12,dtype=torch.float32).reshape(3,4)
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim = 1)

(tensor([[-0.4701,  1.0573,  0.9183, -1.2020],
         [-0.3997,  0.6052,  0.3475,  0.2507],
         [ 0.9713,  0.1753,  0.8392,  0.8772],
         [ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000]]),
 tensor([[-0.4701,  1.0573,  0.9183, -1.2020,  0.0000,  1.0000,  2.0000,  3.0000],
         [-0.3997,  0.6052,  0.3475,  0.2507,  4.0000,  5.0000,  6.0000,  7.0000],
         [ 0.9713,  0.1753,  0.8392,  0.8772,  8.0000,  9.0000, 10.0000, 11.0000]]))

In [5]:
X == Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [6]:
X.sum()

tensor(3.9704)