In [1]:
import torch

In [2]:
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [11]:
c = a + b
c = c.T
c

tensor([[0, 1, 2],
        [1, 2, 3]])

In [14]:
a[-1], c[0:2]

(tensor([2]),
 tensor([[0, 1, 2],
         [1, 2, 3]]))