In [2]:
import torch

In [4]:
X = torch.arange(15).reshape((3, 5))
Y = torch.arange(1, 16).reshape((3, 5))
X == Y, X > Y, X < Y


(tensor([[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]),
 tensor([[False, False, False, False, False],
         [False, False, False, False, False],
         [False, False, False, False, False]]),
 tensor([[True, True, True, True, True],
         [True, True, True, True, True],
         [True, True, True, True, True]]))

In [6]:
a = torch.randn(12).reshape(12,1)
b = torch.randn(12).reshape(1,12)
a + b

tensor([[ 1.4023,  1.7922,  0.5583,  0.7220,  0.2728,  0.2294,  0.8252,  0.6255,
         -0.3301,  1.5404,  1.2986,  1.8839],
        [ 2.1481,  2.5380,  1.3041,  1.4677,  1.0186,  0.9751,  1.5710,  1.3713,
          0.4157,  2.2862,  2.0444,  2.6296],
        [ 0.8031,  1.1930, -0.0410,  0.1227, -0.3264, -0.3699,  0.2260,  0.0263,
         -0.9293,  0.9412,  0.6994,  1.2846],
        [-0.8617, -0.4717, -1.7057, -1.5420, -1.9912, -2.0346, -1.4388, -1.6385,
         -2.5941, -0.7236, -0.9654, -0.3801],
        [ 0.7016,  1.0915, -0.1425,  0.0212, -0.4279, -0.4714,  0.1245, -0.0752,
         -1.0308,  0.8396,  0.5979,  1.1831],
        [ 0.0276,  0.4175, -0.8165, -0.6528, -1.1019, -1.1454, -0.5495, -0.7492,
         -1.7048,  0.1657, -0.0761,  0.5091],
        [-0.3206,  0.0693, -1.1646, -1.0010, -1.4501, -1.4936, -0.8977, -1.0974,
         -2.0530, -0.1825, -0.4243,  0.1609],
        [-1.4236, -1.0337, -2.2676, -2.1039, -2.5531, -2.5965, -2.0007, -2.2004,
         -3.1560, -1.2855, -1.