In [16]:
import torch
x = torch.arange(0, 5, 1.0, requires_grad = True)
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad, y



(tensor([ 0.,  1.,  4.,  9., 16.]),
 tensor([ 0.,  1.,  4.,  9., 16.], grad_fn=<MulBackward0>))

In [17]:
x.grad.zero_()
y.sum().backward()
x.grad

tensor([0., 2., 4., 6., 8.])